### ISSUE TITLE
Crash on query

### ISSUE THREAD

**Issue by jimboca** [UniversalDevicesInc-PG3/udi-poly-Airthings-Consumer#6]
```
2022-07-05 03:04:20,563 MQTT       udi_interface.interface DEBUG    interface:_message: QUEUING incoming message query
2022-07-05 03:04:20,566 Command    udi_interface.interface DEBUG    interface:_parseInput: DEQUEING query
2022-07-05 03:04:20,570 Command    udi_interface      ERROR    udi_interface:write: Exception in thread
2022-07-05 03:04:20,571 Command    udi_interface      ERROR    udi_interface:write: Command
2022-07-05 03:04:20,572 Command    udi_interface      ERROR    udi_interface:write: :
2022-07-05 03:04:20,572 Command    udi_interface      ERROR    udi_interface:write: Traceback (most recent call last):
2022-07-05 03:04:20,573 Command    udi_interface      ERROR    udi_interface:write: File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
2022-07-05 03:04:20,578 Command    udi_interface      ERROR    udi_interface:write: self.run()
2022-07-05 03:04:20,579 Command    udi_interface      ERROR    udi_interface:write: File "/usr/local/lib/python3.8/threading.py", line 870, in run
2022-07-05 03:04:20,583 Command    udi_interface      ERROR    udi_interface:write: self._target(*self._args, **self._kwargs)
2022-07-05 03:04:20,584 Command    udi_interface      ERROR    udi_interface:write: File "/var/polyglot/.local/lib/python3.8/site-packages/udi_interface/interface.py", line 680, in _parseInput
2022-07-05 03:04:20,590 Command    udi_interface      ERROR    udi_interface:write: self._handleInput(key, input[key], None)
2022-07-05 03:04:20,591 Command    udi_interface      ERROR    udi_interface:write: File "/var/polyglot/.local/lib/python3.8/site-packages/udi_interface/interface.py", line 811, in _handleInput
2022-07-05 03:04:20,596 Command    udi_interface      ERROR    udi_interface:write: self.nodes_internal[item['address']].query()
2022-07-05 03:04:20,597 Command    udi_interface      ERROR    udi_interface:write: File "/var/polyglot/pg3/ns/00:0d:b9:52:bf:fc_19/nodes/Controller.py", line 175, in query
2022-07-05 03:04:20,599 Command    udi_interface      ERROR    udi_interface:write: if not self.authorized('query') : return False
2022-07-05 03:04:20,600 Command    udi_interface      ERROR    udi_interface:write: TypeError
2022-07-05 03:04:20,600 Command    udi_interface      ERROR    udi_interface:write: :
2022-07-05 03:04:20,601 Command    udi_interface      ERROR    udi_interface:write: 'bool' object is not callable
```

**Comment by jimboca** [comment]
Fixed in 0.0.6
